// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwbzAUQnWFQ9W8IMVNGMPrZ_OTsjSqo8s',
    appId: '1:712212708387:web:1029372cf20a360f344596',
    messagingSenderId: '712212708387',
    projectId: 'namdeliveryboy',
    authDomain: 'namdeliveryboy.firebaseapp.com',
    storageBucket: 'namdeliveryboy.firebasestorage.app',
    measurementId: 'G-XSBNKYLR7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2SkdZU8aAkdk8EFgHtLCPPplML1u_HD0',
    appId: '1:712212708387:android:5cc188ee14249862344596',
    messagingSenderId: '712212708387',
    projectId: 'namdeliveryboy',
    storageBucket: 'namdeliveryboy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtbn09qDIs-S_-FjFl-Lm303jdha6Rh60',
    appId: '1:712212708387:ios:1a38aec1e8dba645344596',
    messagingSenderId: '712212708387',
    projectId: 'namdeliveryboy',
    storageBucket: 'namdeliveryboy.firebasestorage.app',
    iosBundleId: 'com.workahr.namdelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtbn09qDIs-S_-FjFl-Lm303jdha6Rh60',
    appId: '1:712212708387:ios:1a38aec1e8dba645344596',
    messagingSenderId: '712212708387',
    projectId: 'namdeliveryboy',
    storageBucket: 'namdeliveryboy.firebasestorage.app',
    iosBundleId: 'com.workahr.namdelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwbzAUQnWFQ9W8IMVNGMPrZ_OTsjSqo8s',
    appId: '1:712212708387:web:c2763a3b1cb73dc4344596',
    messagingSenderId: '712212708387',
    projectId: 'namdeliveryboy',
    authDomain: 'namdeliveryboy.firebaseapp.com',
    storageBucket: 'namdeliveryboy.firebasestorage.app',
    measurementId: 'G-QJPKGS0VTB',
  );
}
